# DELETES OLD PLUGIN FILES FROM RPMBUILD ENV
#
##########################################
- name: Remove RPM files on remote server
  hosts: <HOST>
  become: yes
  become_method: sudo
  tasks:
    - name: remove .spec file
      shell: "rm <PATH/TO/RPMBUILD/ENV>/rpmbuild/SPECS/{{ package }}.spec"

    - name: remove .tar.gz file
      shell: "rm <PATH/TO/RPMBUILD/ENV>/rpmbuild/SOURCES/{{ package }}.tar.gz"

    - name: remove RPM file
      shell: "rm <PATH/TO/RPMBUILD/ENV>/rpmbuild/RPMS/noarch/{{ package }}-1.1.0-1.noarch.rpm"
